import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.newReview': 'Neues Review',
    'nav.history': 'Verlauf',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    'nav.admin': 'Admin',
    
    // Dashboard
    'dashboard.title': 'Quartalsrückblick & Marktübersicht',
    'dashboard.subtitle': 'Markt Überblick',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.quarterlyGoal': 'Anstehendes Quartalsziel',
    'dashboard.reviewPast': 'Review vergangenes Quartal',
    'dashboard.startReview': 'Review starten',
    'dashboard.viewHistory': 'Verlauf anzeigen',
    'dashboard.planFor': 'Plan für',
    
    // Market Data
    'market.currencies': 'Währungen & Zinsen',
    'market.exchangeRates': 'Wechselkurse',
    'market.commodities': 'Rohstoffe',
    'market.indices': 'Indizes',
    'market.interestRate': 'Leitzins',
    'market.lastUpdate': 'Letzte Aktualisierung',
    'market.vsLastQuarter': 'vs. Vorquartal',
    'market.vsLastYear': 'vs. Vorjahr',
    'market.q4_2025': 'Q4 2025',
    'market.asOf': 'Stand Q4 2025',
    'market.notifyQ1': 'Benachrichtigen für Q1 26',
    'market.notifySuccess': 'Erinnerung aktiviert',
    'market.notifySuccessDesc': 'Sie werden benachrichtigt, wenn die Q1 2026 Daten verfügbar sind.',
    'market.notifyDisabled': 'Erinnerung deaktiviert',
    'market.notifyDisabledDesc': 'Sie erhalten keine Benachrichtigung für das nächste Quartal.',
    
    // Charts
    'charts.quarterlyDevelopment': 'Quartalsweise Entwicklung',
    'charts.selectMetric': 'Metrik wählen',
    'charts.currencies': 'Währungen',
    'charts.commodities': 'Rohstoffe',
    'charts.indices': 'Indizes',
    'charts.oneYear': '1 Jahr',
    'charts.twoYears': '2 Jahre',
    'charts.all': 'Alle',
    'charts.loadError': 'Quartalsdaten konnten nicht geladen werden',
    'charts.eurToUsd': 'EUR/USD',
    'charts.eurToChf': 'EUR/CHF',
    'charts.eurToHkd': 'EUR/HKD',
    'charts.eurToSek': 'EUR/SEK',
    'charts.oilBrent': 'Öl Brent',
    'charts.oilWTI': 'Öl WTI',
    'charts.gold': 'Gold (XAU)',
    'charts.bitcoin': 'Bitcoin',
    'charts.silver': 'Silber',
    'charts.copper': 'Kupfer',
    'charts.wheat': 'Weizen',
    'charts.dax': 'DAX',
    'charts.sp500': 'S&P 500',
    'charts.nasdaq': 'NASDAQ 100',
    'charts.msciWorld': 'MSCI World',
    
    // Info Section
    'info.title': '20-Minuten-Ritual',
    'info.subtitle': 'Quartalsweise Reflexion für bessere Investitionsentscheidungen',
    'info.bullet1': 'Gesammelte Daten auf einen Blick',
    'info.bullet2': 'Geführte Fragen zur Markteinordnung',
    'info.bullet3': 'Vergleich mit Vorquartalen',
    'info.watchVideo': 'Erklärvideo ansehen',
    'info.videoTitle': 'So funktioniert das 20-Minuten-Ritual',
    'info.videoPlaceholder': 'Video wird geladen...',
    
    // Footer
    'footer.poweredBy': 'Powered by',
    'footer.disclaimer': 'Keine Anlageberatung – Geldanlage mit Rückenwind Navigieren',
    'footer.impressum': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.contact': 'Kontakt',
    
    // Common
    'common.loading': 'Wird geladen...',
    'common.error': 'Fehler',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.refresh': 'Aktualisieren',
    'common.saving': 'Speichere...',
    
    // FocusGoal
    'focusGoal.placeholder': 'z.B. Konsolidierung Bewertung Absicherung',
    'focusGoal.changeGoal': 'Ziel ändern',
    'focusGoal.goalUpdated': 'Quartalsziel wurde aktualisiert.',
    'focusGoal.withEffect': 'Mit Effekt',
    'focusGoal.withoutEffect': 'Ohne Effekt',

    // Index Page
    'index.title': 'Markt-Kompass',
    'index.subtitle': 'Ihr Navigator für smarte Investitionen',
    'index.tagline': 'Geldanlage Selbstbestimmt Reflektieren. Ritual statt Reizüberflutung.',
    'index.startReview': 'Neues Review starten',
    'index.login': 'Anmelden',
    'index.feature1Title': 'Besser einordnen',
    'index.feature1Desc': 'Verstehen Sie Marktbewegungen im Kontext Ihrer langfristigen Strategie',
    'index.feature2Title': 'Klare Entscheidungen',
    'index.feature2Desc': 'Treffen Sie fundierte Anlageentscheidungen basierend auf Quartalsanalysen',
    'index.feature3Title': 'Langfristig denken',
    'index.feature3Desc': 'Trainieren Sie Ihr Urteilsvermögen wie ein Fondsmanager',
    'index.ctaTitle': 'Bereit für Ihr erstes Quartalsreview?',
    'index.ctaSubtitle': '20 Minuten pro Quartal für bessere Investitionsentscheidungen',
    'index.ctaButton': 'Jetzt starten',
    'index.free': '100% Kostenlos',
    
    // Auth Page
    'auth.createAccount': 'Konto erstellen',
    'auth.login': 'Anmelden',
    'auth.signupDesc': 'Erstellen Sie Ihr Konto für quartalsweise Reviews',
    'auth.loginDesc': 'Melden Sie sich an, um fortzufahren',
    'auth.name': 'Name',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.register': 'Registrieren',
    'auth.loading': 'Lädt...',
    'auth.hasAccount': 'Haben Sie bereits ein Konto? Anmelden',
    'auth.noAccount': 'Noch kein Konto? Registrieren',
    'auth.reminderLabel': 'Erinnerung für nä. Quartal',
    'auth.accountCreated': 'Konto erstellt!',
    'auth.accountCreatedDesc': 'Sie können sich jetzt anmelden.',
    'auth.welcomeBack': 'Willkommen zurück!',
    'auth.welcomeBackDesc': 'Sie wurden erfolgreich angemeldet.',
    'auth.error': 'Fehler',
    'auth.continueWithGoogle': 'Mit Google fortfahren',
    'auth.orContinueWith': 'oder',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.resetPassword': 'Passwort zurücksetzen',
    'auth.resetPasswordDesc': 'Geben Sie Ihre E-Mail-Adresse ein, um einen Link zum Zurücksetzen zu erhalten.',
    'auth.sendResetLink': 'Link senden',
    'auth.resetEmailSent': 'E-Mail gesendet',
    'auth.resetEmailSentDesc': 'Prüfen Sie Ihr Postfach für den Reset-Link.',
    'auth.newPassword': 'Neues Passwort',
    'auth.confirmNewPassword': 'Passwort bestätigen',
    'auth.setNewPassword': 'Neues Passwort setzen',
    'auth.passwordUpdated': 'Passwort aktualisiert',
    'auth.passwordUpdatedDesc': 'Sie können sich jetzt mit Ihrem neuen Passwort anmelden.',
    'auth.passwordMismatch': 'Die Passwörter stimmen nicht überein',
    'auth.settingNewPassword': 'Setze neues Passwort...',
    
    // Settings Page
    'settings.appearance': 'Darstellung',
    'settings.appearanceDesc': 'Passen Sie das Erscheinungsbild der Anwendung an',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Dunkles Farbschema aktivieren',
    'settings.profile': 'Profil',
    'settings.profileDesc': 'Ihre Account-Informationen',
    'settings.email': 'E-Mail',
    'settings.notifications': 'Benachrichtigungen',
    'settings.notificationsDesc': 'Verwalten Sie Ihre Erinnerungseinstellungen',
    'settings.quarterlyReminder': 'Quartals-Erinnerung',
    'settings.quarterlyReminderDesc': 'Benachrichtigung bei aktualisierten Zahlen für das nächste Quartal',
    'settings.reminderUpdated': 'Erinnerungseinstellung aktualisiert',
    'settings.security': 'Sicherheit',
    'settings.securityDesc': 'Passwort und Zugangsdaten verwalten',
    'settings.changePassword': 'Passwort ändern',
    'settings.changePasswordDesc': 'Sie erhalten einen Link per E-Mail',
    'settings.passwordResetSent': 'Link gesendet',
    'settings.passwordResetSentDesc': 'Prüfen Sie Ihr Postfach',
    'settings.about': 'Über',
    'settings.aboutDesc': 'Markt-Kompass',
    'settings.aboutText': 'Geldanlage Selbstbestimmt Reflektieren. Ritual statt Reizüberflutung.',
    
    // NewReview Page
    'newReview.title': 'Rückblick',
    'newReview.reviewQ4': 'Rückblick Q4',
    'newReview.subtitle': '20-Minuten-Ritual für bessere Investitionsentscheidungen',
    'newReview.section0': 'Quartals-Reflexion',
    'newReview.section1': 'Währungen & Zinsen',
    'newReview.section2': 'Gold & Silber',
    'newReview.section3': 'Ölpreise',
    'newReview.section4': 'Kupfer & Rohstoffe',
    'newReview.section5': 'Börsen-Indizes',
    'newReview.section6': 'Einzelaktien',
    'newReview.section7': 'Ihre Quartalsstrategie',
    'newReview.sectionA': 'Wechselkurse & Währungen/Zinsen',
    'newReview.sectionB': 'Rohstoffe',
    'newReview.sectionC': 'Aktien & Indizes',
    'newReview.sectionD': 'Gesamt',
    'newReview.observations': 'Beobachtungen',
    'newReview.expandForNotes': 'aufklappen für Notizen',
    'newReview.exportPlan': 'Exportiere jetzt deinen Plan',
    'newReview.remindNextQuarter': 'Erinnere mich zum nächsten Quartal',
    'newReview.autoSaved': 'Automatisch gespeichert',
    'newReview.autoSaveHint': 'Wird automatisch gespeichert',
    'newReview.exportHint': 'Export am Ende der Seite',
    'newReview.draftRestored': 'Entwurf wiederhergestellt',
    'newReview.draftRestoredDesc': 'Ihr bisheriger Fortschritt wurde wiederhergestellt',
    'newReview.popupBlocked': 'Popup wurde blockiert. Bitte erlauben Sie Popups für den PDF-Export.',
    'newReview.aiChat': 'KI-Chat',
    'newReview.aiChatTitle': 'KI-Chat - Reflektieren & Vertiefen',
    'newReview.aiChatDesc': 'Stellen Sie Fragen zu Ihren Daten oder lassen Sie sich bei der Bewertung helfen',
    'newReview.startAnalysis': 'KI-Analyse starten',
    'newReview.analyzing': 'Analysiere...',
    'newReview.helpfulQuestions': 'Hilfreiche Fragen',
    'newReview.generating': 'Generiere...',
    'newReview.you': 'Sie',
    'newReview.aiAssistant': 'KI-Assistent',
    'newReview.followUpPlaceholder': 'z.B. \'Ich habe gesehen, dass Kupfer gestiegen ist. Ist das ein Risiko oder eher neutral?\'',
    
    // NewReview Labels
    'newReview.q0_keywords': 'Was hat dieses Quartal dominiert? (max. 3 Schlagworte)',
    'newReview.q0_keywordsPlaceholder': 'z.B. KI-Boom, Zinswende, Geopolitik',
    'newReview.q0_event': 'Welches Ereignis hat Ihre Aufmerksamkeit besonders gefordert?',
    'newReview.q0_eventPlaceholder': 'Beschreiben Sie das wichtigste Ereignis...',
    'newReview.q0_stable': 'Was war überraschend stabil – trotz Krisen oder Hype?',
    'newReview.q0_stablePlaceholder': 'Was hat Sie positiv überrascht...',
    'newReview.q0_insight': 'Welche persönliche Erkenntnis war für Sie besonders wertvoll?',
    'newReview.q0_insightPlaceholder': 'Ihre wichtigste Erkenntnis...',
    'newReview.q1_notes': 'Notizen zu Währungen (USD/EUR/CHF) und Leitzinsen',
    'newReview.q1_notesPlaceholder': 'z.B. USD Leitzins 5.25%, EUR 4.5%, CHF 1.75%...',
    'newReview.q1_reflection': 'Welche Zinspolitik bereitet Ihnen Sorgen oder Chancen?',
    'newReview.q1_reflectionPlaceholder': 'Ihre Gedanken zur Zinspolitik...',
    'newReview.q2_notes': 'Notizen zu Edelmetallen (Gold, Silber)',
    'newReview.q2_notesPlaceholder': 'z.B. Gold 2050 USD/oz (+5%), Silber 24 USD/oz...',
    'newReview.q2_reflection': 'Wie denken Sie aktuell über Edelmetalle als Absicherung?',
    'newReview.q2_reflectionPlaceholder': 'Ihre Einschätzung zu Edelmetallen...',
    'newReview.q3_notes': 'Notizen zu Ölpreisen (Brent, WTI)',
    'newReview.q3_notesPlaceholder': 'z.B. Brent 85 USD/Barrel, WTI 81 USD/Barrel...',
    'newReview.q3_reflection': 'Erwarten Sie politische Eingriffe oder Angebotsverzerrungen?',
    'newReview.q3_reflectionPlaceholder': 'Ihre Gedanken zu Ölmärkten...',
    'newReview.q4_notes': 'Notizen zu Kupfer und anderen Rohstoffen',
    'newReview.q4_notesPlaceholder': 'z.B. Kupfer 8500 USD/t (+3%), Lithium...',
    'newReview.q4_reflection': 'Wie stark beeinflusst Rohstoffknappheit Ihre Investmentüberlegungen?',
    'newReview.q4_reflectionPlaceholder': 'Ihre Einschätzung zu Rohstoffen...',
    'newReview.q5_notes': 'Notizen zu Indizes (DAX, S&P 500, MSCI World)',
    'newReview.q5_notesPlaceholder': 'z.B. DAX 18500 (+8%), S&P 500 5200...',
    'newReview.q5_reflection': 'Wie bewerten Sie die aktuelle Marktpsychologie?',
    'newReview.q5_reflectionPlaceholder': 'Ihre Einschätzung zur Marktstimmung...',
    'newReview.q6_notes': 'Notizen zu wichtigen Einzelaktien',
    'newReview.q6_notesPlaceholder': 'z.B. Apple 180 USD (+12%), Microsoft...',
    'newReview.q6_reflection': 'Welche Position verdient mehr Aufmerksamkeit? Wo möchten Sie reduzieren?',
    'newReview.q6_reflectionPlaceholder': 'Ihre Überlegungen zu Einzelpositionen...',
    'newReview.q7_strengthens': 'Was stärkt Ihre Strategie langfristig?',
    'newReview.q7_strengthensPlaceholder': 'Was bestärkt Sie in Ihrer Anlagestrategie...',
    'newReview.q7_uncertainties': 'Was verunsichert Sie?',
    'newReview.q7_uncertaintiesPlaceholder': 'Ihre Bedenken und Unsicherheiten...',
    'newReview.q7_changes': 'Was möchten Sie im nächsten Quartal anders machen?',
    'newReview.q7_changesPlaceholder': 'Geplante Änderungen für Q...',
    
    // Toast messages
    'toast.noNotes': 'Keine Notizen',
    'toast.noNotesDesc': 'Bitte füllen Sie mindestens einige Felder aus',
    'toast.aiGenerated': 'KI-Analyse generiert',
    'toast.aiGeneratedDesc': 'Die Schlussfolgerungen wurden erfolgreich erstellt',
    'toast.aiError': 'KI-Analyse konnte nicht generiert werden',
    'toast.followUpError': 'Rückfrage konnte nicht bearbeitet werden',
    'toast.questionsGenerated': 'Vorschläge generiert',
    'toast.questionsGeneratedDesc': 'Hilfreiche Fragen wurden erstellt',
    'toast.questionsError': 'Fragen konnten nicht generiert werden',
    'toast.notLoggedIn': 'Nicht angemeldet',
    'toast.notLoggedInDesc': 'Bitte melden Sie sich an, um Reviews zu speichern',
    'toast.noData': 'Keine Daten',
    'toast.noDataDesc': 'Bitte füllen Sie mindestens einige Felder aus',
    'toast.reviewSaved': 'Review gespeichert',
    'toast.reviewSavedDesc': 'Ihr Review wurde erfolgreich gespeichert',
    'toast.reviewError': 'Review konnte nicht gespeichert werden',
    
    // History
    'history.title': 'Ihre Quartalsreviews',
    'history.loading': 'Lädt...',
    'history.reviewsCount': 'Reviews gespeichert',
    'history.noReviews': 'Noch keine Reviews',
    'history.startFirst': 'Starten Sie Ihr erstes Quartalsreview',
    'history.newReview': 'Neues Review starten',
    'history.viewReview': 'Review ansehen',
    'history.updateReview': 'Review bearbeiten',
    'history.uploadPastReview': 'Vergangenes Review hochladen',
    'history.createdOn': 'Erstellt am',
    'history.documentUploaded': 'Dokument hochgeladen',
    'history.uploadSuccess': 'Dokument hochgeladen',
    'history.uploadSuccessDesc': 'wurde erfolgreich hinzugefügt.',
    'history.uploadError': 'Fehler beim Hochladen',
    'history.loadError': 'Fehler beim Laden',
    'history.collectThoughts': 'Gedanken für Q1 26 sammeln',
    'history.collectThoughtsActive': 'Gedanken für das aktive Quartal sammeln',
    'history.collectThoughtsDesc': 'Notieren Sie laufende Beobachtungen und Gedanken – unabhängig von Ihren Reviews.',
    'history.startCollecting': 'Öffnen',
    'history.closeModal': 'Schließen',
    'history.noDataAvailable': 'Keine Daten verfügbar',
    'history.selectQuarterForUpload': 'Wählen Sie das Quartal für den Upload',
    'history.clickToUploadPDF': 'Klicken Sie hier um eine PDF-Datei hochzuladen',
    'history.thoughtsPlaceholder': 'Notieren Sie hier Ihre Beobachtungen und Gedanken für das laufende Quartal...',
    'history.noNotesYet': 'Noch keine Notizen für dieses Quartal',
    'history.addNotes': 'Notizen hinzufügen',
    'history.restartReview': 'Review Neustarten',
    'history.openPDF': 'PDF öffnen',
    
    // Cookie Banner
    'cookies.title': 'Diese Website verwendet Cookies',
    'cookies.description': 'Wir nutzen Cookies, um Ihnen die bestmögliche Erfahrung zu bieten. Essenzielle Cookies sind für die Grundfunktionen erforderlich. Sie können zusätzlich Marketing- und Statistik-Cookies aktivieren.',
    'cookies.essential': 'Essenzielle Cookies',
    'cookies.essentialDesc': 'Notwendig für grundlegende Funktionen',
    'cookies.marketing': 'Marketing Cookies',
    'cookies.marketingDesc': 'Für personalisierte Werbung',
    'cookies.statistics': 'Statistik Cookies',
    'cookies.statisticsDesc': 'Zur Analyse der Websitenutzung',
    'cookies.acceptAll': 'Alle akzeptieren',
    'cookies.acceptSelected': 'Auswahl akzeptieren',
    'cookies.showDetails': 'Details anzeigen',
    'cookies.hideDetails': 'Details ausblenden',
    
    // Contact Page
    'contact.availability': 'Erreichbarkeit',
    'contact.availabilityHours': 'Montag - Freitag: 9:00 - 17:00 Uhr',
    'contact.availabilityResponse': 'Wir bemühen uns, Ihre Anfragen innerhalb von 24 Stunden zu beantworten.',
    'contact.feedbackTitle': 'Was sollen wir hinzufügen?',
    'contact.feedbackDesc': 'Helfen Sie uns, die App zu verbessern',
    'contact.feedback.stocks': 'Eigene Aktienpositionen hinzufügen',
    'contact.feedback.tradelog': 'Trade Log hinzufügen (Zu-/Verkäufe)',
    'contact.feedback.allocation': 'Vermögensallokation',
    'contact.feedback.moreCommodities': 'Weitere Rohstoffe',
    'contact.feedback.moreIndices': 'Weitere Indizes',
    'contact.feedback.moreCurrencies': 'Weitere Währungen',
    'contact.feedback.other': 'Sonstiges',
    'contact.feedback.otherPlaceholder': 'Weitere Ideen oder Anmerkungen...',
    'contact.feedback.submit': 'Feedback senden',
    'contact.feedbackSent': 'Feedback gesendet',
    'contact.feedbackSentDesc': 'Vielen Dank für Ihr Feedback!',
    
    // Common additions
    'common.close': 'Schließen',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.newReview': 'New Review',
    'nav.history': 'History',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    
    // Dashboard
    'dashboard.title': 'Quarterly Review & Market Overview',
    'dashboard.subtitle': 'Quarterly Market Snapshot',
    'dashboard.welcome': 'Welcome back',
    'dashboard.quarterlyGoal': 'Upcoming Quarterly Goal',
    'dashboard.reviewPast': 'Review Past Quarter',
    'dashboard.startReview': 'Start Review',
    'dashboard.viewHistory': 'View History',
    'dashboard.planFor': 'Plan for',
    
    // Market Data
    'market.currencies': 'Currencies & Interest Rates',
    'market.exchangeRates': 'Exchange Rates',
    'market.commodities': 'Commodities',
    'market.indices': 'Indices',
    'market.interestRate': 'Interest Rate',
    'market.lastUpdate': 'Last Update',
    'market.vsLastQuarter': 'vs. Last Quarter',
    'market.vsLastYear': 'vs. Last Year',
    'market.q4_2025': 'Q4 2025',
    'market.asOf': 'As of Q4 2025',
    'market.notifyQ1': 'Notify for Q1 26',
    'market.notifySuccess': 'Reminder activated',
    'market.notifySuccessDesc': 'You will be notified when Q1 2026 data is available.',
    'market.notifyDisabled': 'Reminder disabled',
    'market.notifyDisabledDesc': 'You will not receive a notification for the next quarter.',
    
    // Charts
    'charts.quarterlyDevelopment': 'Quarterly Development',
    'charts.selectMetric': 'Select Metric',
    'charts.currencies': 'Currencies',
    'charts.commodities': 'Commodities',
    'charts.indices': 'Indices',
    'charts.oneYear': '1 Year',
    'charts.twoYears': '2 Years',
    'charts.all': 'All',
    'charts.loadError': 'Could not load quarterly data',
    'charts.eurToUsd': 'EUR/USD',
    'charts.eurToChf': 'EUR/CHF',
    'charts.eurToHkd': 'EUR/HKD',
    'charts.eurToSek': 'EUR/SEK',
    'charts.oilBrent': 'Brent Oil',
    'charts.oilWTI': 'WTI Oil',
    'charts.gold': 'Gold (XAU)',
    'charts.bitcoin': 'Bitcoin',
    'charts.silver': 'Silver',
    'charts.copper': 'Copper',
    'charts.wheat': 'Wheat',
    'charts.dax': 'DAX',
    'charts.sp500': 'S&P 500',
    'charts.nasdaq': 'NASDAQ 100',
    'charts.msciWorld': 'MSCI World',
    
    // Info Section
    'info.title': '20-Minute Ritual',
    'info.subtitle': 'Quarterly reflection for better investment decisions',
    'info.bullet1': 'All data at a glance',
    'info.bullet2': 'Guided questions for market context',
    'info.bullet3': 'Comparison with previous quarters',
    'info.watchVideo': 'Watch explainer video',
    'info.videoTitle': 'How the 20-Minute Ritual Works',
    'info.videoPlaceholder': 'Loading video...',
    
    // Footer
    'footer.poweredBy': 'Powered by',
    'footer.disclaimer': 'Not investment advice – Navigate Investing with Tailwind',
    'footer.impressum': 'Legal Notice',
    'footer.privacy': 'Privacy',
    'footer.contact': 'Contact',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.refresh': 'Refresh',
    'common.saving': 'Saving...',
    
    // FocusGoal
    'focusGoal.placeholder': 'e.g. Consolidation Valuation Hedging',
    'focusGoal.changeGoal': 'Change goal',
    'focusGoal.goalUpdated': 'Quarterly goal has been updated.',
    'focusGoal.withEffect': 'With Effect',
    'focusGoal.withoutEffect': 'Without Effect',

    // Index Page
    'index.title': 'Market Compass',
    'index.subtitle': 'Your Navigator for Smart Investments',
    'index.tagline': 'Self-Directed Investment Reflection. Ritual over Information Overload.',
    'index.startReview': 'Start New Review',
    'index.login': 'Login',
    'index.feature1Title': 'Better Context',
    'index.feature1Desc': 'Understand market movements in the context of your long-term strategy',
    'index.feature2Title': 'Clear Decisions',
    'index.feature2Desc': 'Make informed investment decisions based on quarterly analyses',
    'index.feature3Title': 'Think Long-Term',
    'index.feature3Desc': 'Train your judgment like a fund manager',
    'index.ctaTitle': 'Ready for your first quarterly review?',
    'index.ctaSubtitle': '20 minutes per quarter for better investment decisions',
    'index.ctaButton': 'Get Started',
    'index.free': '100% Free',
    
    // Auth Page
    'auth.createAccount': 'Create Account',
    'auth.login': 'Login',
    'auth.signupDesc': 'Create your account for quarterly reviews',
    'auth.loginDesc': 'Login to continue',
    'auth.name': 'Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.register': 'Register',
    'auth.loading': 'Loading...',
    'auth.hasAccount': 'Already have an account? Login',
    'auth.noAccount': 'No account yet? Register',
    'auth.reminderLabel': 'Reminder for next quarter',
    'auth.accountCreated': 'Account created!',
    'auth.accountCreatedDesc': 'You can now log in.',
    'auth.welcomeBack': 'Welcome back!',
    'auth.welcomeBackDesc': 'You have been successfully logged in.',
    'auth.error': 'Error',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.orContinueWith': 'or',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordDesc': 'Enter your email address to receive a reset link.',
    'auth.sendResetLink': 'Send Link',
    'auth.resetEmailSent': 'Email sent',
    'auth.resetEmailSentDesc': 'Check your inbox for the reset link.',
    'auth.newPassword': 'New Password',
    'auth.confirmNewPassword': 'Confirm Password',
    'auth.setNewPassword': 'Set New Password',
    'auth.passwordUpdated': 'Password Updated',
    'auth.passwordUpdatedDesc': 'You can now log in with your new password.',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.settingNewPassword': 'Setting new password...',
    
    // Settings Page
    'settings.appearance': 'Appearance',
    'settings.appearanceDesc': 'Customize the look of the application',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Enable dark color scheme',
    'settings.profile': 'Profile',
    'settings.profileDesc': 'Your account information',
    'settings.email': 'Email',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Manage your reminder settings',
    'settings.quarterlyReminder': 'Quarterly Reminder',
    'settings.quarterlyReminderDesc': 'Get notified with updated numbers for next quarter',
    'settings.reminderUpdated': 'Reminder setting updated',
    'settings.security': 'Security',
    'settings.securityDesc': 'Manage your password and credentials',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDesc': 'You will receive a link via email',
    'settings.passwordResetSent': 'Link sent',
    'settings.passwordResetSentDesc': 'Check your inbox',
    'settings.about': 'About',
    'settings.aboutDesc': 'Market Compass',
    'settings.aboutText': 'Self-Directed Investment Reflection. Ritual over Information Overload.',
    
    // NewReview Page
    'newReview.title': 'Review',
    'newReview.reviewQ4': 'Review Q4',
    'newReview.subtitle': '20-minute ritual for better investment decisions',
    'newReview.section0': 'Quarterly Reflection',
    'newReview.section1': 'Currencies & Interest Rates',
    'newReview.section2': 'Gold & Silver',
    'newReview.section3': 'Oil Prices',
    'newReview.section4': 'Copper & Commodities',
    'newReview.section5': 'Stock Indices',
    'newReview.section6': 'Individual Stocks',
    'newReview.section7': 'Your Quarterly Strategy',
    'newReview.sectionA': 'Exchange Rates & Currencies/Interest',
    'newReview.sectionB': 'Commodities',
    'newReview.sectionC': 'Stocks & Indices',
    'newReview.sectionD': 'Summary',
    'newReview.observations': 'Observations',
    'newReview.expandForNotes': 'expand for notes',
    'newReview.exportPlan': 'Export your plan',
    'newReview.remindNextQuarter': 'Remind me for next quarter',
    'newReview.autoSaved': 'Auto-saved',
    'newReview.autoSaveHint': 'Auto-saved',
    'newReview.exportHint': 'Export at bottom of page',
    'newReview.draftRestored': 'Draft restored',
    'newReview.draftRestoredDesc': 'Your previous progress has been restored',
    'newReview.popupBlocked': 'Popup was blocked. Please allow popups for PDF export.',
    'newReview.aiChat': 'AI Chat',
    'newReview.aiChatTitle': 'AI Chat - Reflect & Deepen',
    'newReview.aiChatDesc': 'Ask questions about your data or get help with your evaluation',
    'newReview.startAnalysis': 'Start AI Analysis',
    'newReview.analyzing': 'Analyzing...',
    'newReview.helpfulQuestions': 'Helpful Questions',
    'newReview.generating': 'Generating...',
    'newReview.you': 'You',
    'newReview.aiAssistant': 'AI Assistant',
    'newReview.followUpPlaceholder': 'e.g. \'I saw that copper has risen. Is that a risk or rather neutral?\'',
    
    // NewReview Labels
    'newReview.q0_keywords': 'What dominated this quarter? (max. 3 keywords)',
    'newReview.q0_keywordsPlaceholder': 'e.g. AI boom, interest rate reversal, geopolitics',
    'newReview.q0_event': 'Which event particularly demanded your attention?',
    'newReview.q0_eventPlaceholder': 'Describe the most important event...',
    'newReview.q0_stable': 'What was surprisingly stable – despite crises or hype?',
    'newReview.q0_stablePlaceholder': 'What positively surprised you...',
    'newReview.q0_insight': 'Which personal insight was particularly valuable for you?',
    'newReview.q0_insightPlaceholder': 'Your most important insight...',
    'newReview.q1_notes': 'Notes on currencies (USD/EUR/CHF) and key interest rates',
    'newReview.q1_notesPlaceholder': 'e.g. USD key rate 5.25%, EUR 4.5%, CHF 1.75%...',
    'newReview.q1_reflection': 'Which interest rate policy concerns or offers opportunities?',
    'newReview.q1_reflectionPlaceholder': 'Your thoughts on interest rate policy...',
    'newReview.q2_notes': 'Notes on precious metals (Gold, Silver)',
    'newReview.q2_notesPlaceholder': 'e.g. Gold 2050 USD/oz (+5%), Silver 24 USD/oz...',
    'newReview.q2_reflection': 'How do you currently think about precious metals as a hedge?',
    'newReview.q2_reflectionPlaceholder': 'Your assessment of precious metals...',
    'newReview.q3_notes': 'Notes on oil prices (Brent, WTI)',
    'newReview.q3_notesPlaceholder': 'e.g. Brent 85 USD/Barrel, WTI 81 USD/Barrel...',
    'newReview.q3_reflection': 'Do you expect political interventions or supply distortions?',
    'newReview.q3_reflectionPlaceholder': 'Your thoughts on oil markets...',
    'newReview.q4_notes': 'Notes on copper and other commodities',
    'newReview.q4_notesPlaceholder': 'e.g. Copper 8500 USD/t (+3%), Lithium...',
    'newReview.q4_reflection': 'How strongly does commodity scarcity affect your investment considerations?',
    'newReview.q4_reflectionPlaceholder': 'Your assessment of commodities...',
    'newReview.q5_notes': 'Notes on indices (DAX, S&P 500, MSCI World)',
    'newReview.q5_notesPlaceholder': 'e.g. DAX 18500 (+8%), S&P 500 5200...',
    'newReview.q5_reflection': 'How do you assess the current market psychology?',
    'newReview.q5_reflectionPlaceholder': 'Your assessment of market sentiment...',
    'newReview.q6_notes': 'Notes on important individual stocks',
    'newReview.q6_notesPlaceholder': 'e.g. Apple 180 USD (+12%), Microsoft...',
    'newReview.q6_reflection': 'Which position deserves more attention? Where would you like to reduce?',
    'newReview.q6_reflectionPlaceholder': 'Your considerations on individual positions...',
    'newReview.q7_strengthens': 'What strengthens your strategy long-term?',
    'newReview.q7_strengthensPlaceholder': 'What reinforces your investment strategy...',
    'newReview.q7_uncertainties': 'What unsettles you?',
    'newReview.q7_uncertaintiesPlaceholder': 'Your concerns and uncertainties...',
    'newReview.q7_changes': 'What would you like to do differently next quarter?',
    'newReview.q7_changesPlaceholder': 'Planned changes for Q...',
    
    // Toast messages
    'toast.noNotes': 'No notes',
    'toast.noNotesDesc': 'Please fill in at least some fields',
    'toast.aiGenerated': 'AI analysis generated',
    'toast.aiGeneratedDesc': 'The conclusions have been successfully created',
    'toast.aiError': 'AI analysis could not be generated',
    'toast.followUpError': 'Follow-up question could not be processed',
    'toast.questionsGenerated': 'Suggestions generated',
    'toast.questionsGeneratedDesc': 'Helpful questions have been created',
    'toast.questionsError': 'Questions could not be generated',
    'toast.notLoggedIn': 'Not logged in',
    'toast.notLoggedInDesc': 'Please log in to save reviews',
    'toast.noData': 'No data',
    'toast.noDataDesc': 'Please fill in at least some fields',
    'toast.reviewSaved': 'Review saved',
    'toast.reviewSavedDesc': 'Your review has been successfully saved',
    'toast.reviewError': 'Review could not be saved',
    
    // History
    'history.title': 'Your Quarterly Reviews',
    'history.loading': 'Loading...',
    'history.reviewsCount': 'reviews saved',
    'history.noReviews': 'No reviews yet',
    'history.startFirst': 'Start your first quarterly review',
    'history.newReview': 'Start New Review',
    'history.viewReview': 'View Review',
    'history.updateReview': 'Edit Review',
    'history.uploadPastReview': 'Upload Past Review',
    'history.createdOn': 'Created on',
    'history.documentUploaded': 'Document uploaded',
    'history.uploadSuccess': 'Document uploaded',
    'history.uploadSuccessDesc': 'was successfully added.',
    'history.uploadError': 'Upload failed',
    'history.loadError': 'Failed to load',
    'history.collectThoughts': 'Collect thoughts for Q1 26',
    'history.collectThoughtsActive': 'Collect thoughts for the active quarter',
    'history.collectThoughtsDesc': 'Record ongoing observations and thoughts – independent of your reviews.',
    'history.startCollecting': 'Open',
    'history.closeModal': 'Close',
    'history.noDataAvailable': 'No data available',
    'history.selectQuarterForUpload': 'Select the quarter for upload',
    'history.clickToUploadPDF': 'Click here to upload a PDF file',
    'history.thoughtsPlaceholder': 'Note your observations and thoughts for the current quarter here...',
    'history.noNotesYet': 'No notes for this quarter yet',
    'history.addNotes': 'Add notes',
    'history.restartReview': 'Restart Review',
    'history.openPDF': 'Open PDF',
    
    // Cookie Banner
    'cookies.title': 'This website uses cookies',
    'cookies.description': 'We use cookies to provide you with the best experience. Essential cookies are required for basic functions. You can also enable marketing and statistics cookies.',
    'cookies.essential': 'Essential Cookies',
    'cookies.essentialDesc': 'Required for basic functionality',
    'cookies.marketing': 'Marketing Cookies',
    'cookies.marketingDesc': 'For personalized advertising',
    'cookies.statistics': 'Statistics Cookies',
    'cookies.statisticsDesc': 'For analyzing website usage',
    'cookies.acceptAll': 'Accept All',
    'cookies.acceptSelected': 'Accept Selected',
    'cookies.showDetails': 'Show Details',
    'cookies.hideDetails': 'Hide Details',
    
    // Contact Page
    'contact.availability': 'Availability',
    'contact.availabilityHours': 'Monday - Friday: 9:00 AM - 5:00 PM',
    'contact.availabilityResponse': 'We strive to respond to your inquiries within 24 hours.',
    'contact.feedbackTitle': 'What should we add?',
    'contact.feedbackDesc': 'Help us improve the app',
    'contact.feedback.stocks': 'Add own stock positions',
    'contact.feedback.tradelog': 'Add trade log (buys/sells)',
    'contact.feedback.allocation': 'Asset allocation',
    'contact.feedback.moreCommodities': 'More commodities',
    'contact.feedback.moreIndices': 'More indices',
    'contact.feedback.moreCurrencies': 'More currencies',
    'contact.feedback.other': 'Other',
    'contact.feedback.otherPlaceholder': 'Other ideas or suggestions...',
    'contact.feedback.submit': 'Send Feedback',
    'contact.feedbackSent': 'Feedback sent',
    'contact.feedbackSentDesc': 'Thank you for your feedback!',
    
    // Common additions
    'common.close': 'Close',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('kasona-language');
    return (saved as Language) || 'de';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('kasona-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['de']] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};